namespace: default

nameOverride: "opal"

# Service account for the Rock spawner
# This is gives the permission to the Opal server to spawn new Rock containers
serviceAccount:
  name: rock-spawner-service-account

# MongoDB setup: enable if MongoDB is externally managed
useMongo: false

# MongoDB configuration
mongo:
  # Enable internally managed MongoDB
  enabled: true
  image: mongo:8.0
  pvcSize: 1Gi
  # Storage class for the PVC (leave empty for default storage class)
  storageClassName: ""
  # MongoDB connection details (internal or external)
  host: mongo
  port: "27017"
  database: opal
  username: root
  password: example

# PostgreSQL setup: enable if PostgreSQL is externally managed
usePostgres: false

# PostgreSQL configuration
postgres:
  data:
    # Enable internally managed PostgreSQL
    enabled: false
    image: postgres:15
    pvcSize: 1Gi
    # Storage class for the PVC (leave empty for default storage class)
    storageClassName: ""
    # PostgreSQL connection details (internal or external)
    host: postgres
    port: "5432"
    username: postgres
    password: example
    database: opaldb

# Opal configuration
opal:
  # Container image configuration
  image: obiba/opal:latest
  imagePullPolicy: Always
  # Opal PVC size for persistent storage of configuration files and runtime work directory 
  pvcSize: 1Gi
  # Storage class for the PVC (leave empty for default storage class)
  storageClassName: ""
  # Java options
  javaOpts: "-Xms1G -Xmx2G -XX:+UseG1GC"
  # Opal administrator password
  adminPassword: password
  resources:
    # Requested resources at pod start  
    requests:
      memory: 1Gi
      cpu: "1"
    # Limits of the resources used by the pod
    limits:
      memory: 2Gi
      cpu: "2"
  rock:
    # Comma separated list of allowed Rock images
    imagesAllowed: ""
    # Default Rock container pods specifications
    specs:
      - id: default # Identifier of the R server profile, it is required to have at least a profile with the "default" name
        type: rock # Required
        # When enabled, Opal will use this specification to spawn new Rock containers
        enabled: true
        container:
            # Pod name prefix
            name: default
            # Container image
            image: datashield/rock-base:latest
            # Container image pull policy
            imagePullPolicy: IfNotPresent
            # Container port (necessarily 8085 for Rock)
            port: 8085
            resources:
                # Requested resources at pod start
                requests:
                    cpu: 2000m
                    memory: 500Mi
                # Limits of the resources used by the pod
                limits:
                    cpu: 2000m
                    memory: 1Gi

# Ingress configuration
ingress:
  # Enable internally managed Ingress
  enabled: false
  # Ingress class name, e.g., "nginx"
  className: "nginx"
  # Extra annotations like cert-manager etc.
  annotations: {}
  hosts:
    - host: opal.local
      paths:
        - path: /
          pathType: Prefix
  # TLS configuration, e.g. for cert-manager
  tls: []
