namespace: default

nameOverride: "opal"

# Service account for the Rock spawner
serviceAccount:
  name: rock-spawner-service-account

# MongoDB setup: enable if MongoDB is externally managed
useMongo: false

# MongoDB configuration
mongo:
  # Enable internally managed MongoDB
  enabled: true
  image: mongo:8.0
  pvcSize: 1Gi
  # MongoDB connection details (internal or external)
  host: mongo
  port: "27017"
  database: opal
  username: root
  password: example

# PostgreSQL setup: enable if PostgreSQL is externally managed
usePostgres: false

# PostgreSQL configuration
postgres:
  data:
    # Enable internally managed PostgreSQL
    enabled: false
    image: postgres:15
    pvcSize: 1Gi
    # PostgreSQL connection details (internal or external)
    host: postgres
    port: "5432"
    username: postgres
    password: example
    database: opaldb

# Opal configuration
opal:
  image: obiba/opal:snapshot
  imagePullPolicy: Always
  pvcSize: 1Gi
  javaOpts: "-Xms1G -Xmx2G -XX:+UseG1GC"
  adminPassword: password
  resources:
    requests:
      memory: 1Gi
      cpu: "1"
    limits:
      memory: 2Gi
      cpu: "2"
  rock:
    imagesAllowed: ""
    specs:
      - id: default
        type: rock
        enabled: true
        container:
            name: default
            image: datashield/rock-base:latest
            imagePullPolicy: IfNotPresent
            port: 8085
            resources:
                requests:
                    cpu: 1000m
                    memory: 500Mi
                limits:
                    cpu: 1000m
                    memory: 1Gi

# Ingress configuration
ingress:
  # Enable internally managed Ingress
  enabled: false
  # Ingress class name, e.g., "nginx"
  className: "nginx"
  # Extra annotations like cert-manager etc.
  annotations: {}
  hosts:
    - host: opal.local
      paths:
        - path: /
          pathType: Prefix
  # TLS configuration, e.g. for cert-manager
  tls: []
