{{- if .Values.mongo.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mongo.name }}
  labels:
    {{- include "mongo.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Values.mongo.name }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "mongo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mongo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo.image }}
          ports:
            - containerPort: {{ .Values.mongo.port | default "27017" }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
          {{- if or .Values.mongo.existingSecret .Values.global.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongo.existingSecret | default .Values.global.existingSecret }}
                  key: {{ .Values.mongo.existingSecretKeys.user }}
          {{- else }}
              value: {{ .Values.mongo.user | quote }}
          {{- end }}
            - name: MONGO_INITDB_ROOT_PASSWORD
          {{- if or .Values.mongo.existingSecret .Values.global.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongo.existingSecret | default .Values.global.existingSecret }}
                  key: {{ .Values.mongo.existingSecretKeys.password }}
          {{- else }}
              value: {{ .Values.mongo.password | quote }}
          {{- end }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.mongo.port | default "27017" }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - "mongosh --host localhost --port 27017 -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval 'db.runCommand(\"ping\")'"
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
        labels:
          {{- include "mongo.pvc.labels" . | nindent 10 }}
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.global.storageClassName }}
        storageClassName: {{ .Values.global.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.mongo.pvcSize | default "1Gi" }}
{{- end }}