{{- if .Values.mongo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    {{- include "mongo.labels" . | nindent 4 }}
spec:
  ports:
    - port: 27017
  selector:
    {{- include "mongo.selectorLabels" . | nindent 4 }}
{{- end }}