apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "opal.name" . }}
  labels:
    {{- include "opal.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "opal.name" . }}
  replicas: 1
  selector:
    matchLabels:
      app: opal
  template:
    metadata:
      labels:
        app: opal
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: opal
          image: {{ .Values.opal.image }}
          imagePullPolicy: {{ .Values.opal.imagePullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: {{ .Values.opal.javaOpts }}
            - name: OPAL_ADMINISTRATOR_PASSWORD
              value: {{ .Values.opal.adminPassword }}
          {{- if or .Values.usePostgres .Values.postgres.data.enabled }}
            - name: POSTGRESDATA_HOST
              value: {{ .Values.postgres.data.host | default "postgres" }}
            - name: POSTGRESDATA_PORT
              value: "{{ .Values.postgres.data.port }}"
            - name: POSTGRESDATA_USER
              value: {{ .Values.postgres.data.username }}
            - name: POSTGRESDATA_PASSWORD
              value: {{ .Values.postgres.data.password }}
            - name: POSTGRESDATA_DATABASE
              value: {{ .Values.postgres.data.database }}
          {{- end }}
          {{- if or .Values.useMongo .Values.mongo.enabled }}
            - name: MONGO_HOST
              value: {{ .Values.mongo.host | default "mongo" }}
            - name: MONGO_PORT
              value: "{{ .Values.mongo.port }}"
            - name: MONGODATA_DATABASE
              value: {{ .Values.mongo.database | default "opal" }}
            - name: MONGO_USER
              value: {{ .Values.mongo.username }}
            - name: MONGO_PASSWORD
              value: {{ .Values.mongo.password }}
          {{- end }}
            - name: ROCK_HOSTS
              value: ""
          {{- if .Values.opal.rock.imagesAllowed }}
            - name: ROCK_POD_IMAGES_ALLOWED
              value: {{ .Values.opal.rock.imagesAllowed }}
          {{- end }}
          {{- if .Values.opal.rock.specs }}
            - name: ROCK_POD_SPECS
              value: {{ .Values.opal.rock.specs | toJson | quote }}
          {{- end }}
          volumeMounts:
            - name: opal-storage
              mountPath: /srv
          resources:
            requests:
              memory: {{ .Values.opal.resources.requests.memory | default "1Gi" }}
              cpu: {{ .Values.opal.resources.requests.cpu | default "1" }}
            limits:
              memory: {{ .Values.opal.resources.limits.memory | default "2Gi" }}
              cpu: {{ .Values.opal.resources.limits.cpu | default "2" }}
  volumeClaimTemplates:
    - metadata:
        name: opal-storage
        labels:
          {{- include "opal.labels" . | nindent 10 }}
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.opal.storageClassName }}
        storageClassName: {{ .Values.opal.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.opal.pvcSize | default "1Gi" }}
