apiVersion: v1
kind: Service
metadata:
  name: {{ include "opal.name" . }}
  labels:
    {{ include "opal.labels" . | indent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: opal
