{{- if and .Values.opal.backup.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opal-backup
  labels:
    app: {{ include "opal.name" . }}
    component: backup
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.global.storageClassName }}
  storageClassName: {{ .Values.global.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.opal.backup.pvcSize | default "2Gi" }}
{{- end }}
