{{- if .Values.postgres.ids.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgres.ids.name }}
  labels:
    {{- include "postgres.ids.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Values.postgres.ids.name }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "postgres.ids.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgres.ids.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.ids.image }}
          ports:
            - containerPort: {{ .Values.postgres.ids.port | default "5432" }}
          env:
            - name: POSTGRES_USER
          {{- if or .Values.postgres.ids.existingSecret .Values.global.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.ids.existingSecret | default .Values.global.existingSecret }}
                  key: {{ .Values.postgres.ids.existingSecretKeys.user }}
          {{- else }}
              value: {{ .Values.postgres.ids.user | quote }}
          {{- end }}
            - name: POSTGRES_PASSWORD
          {{- if or .Values.postgres.ids.existingSecret .Values.global.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.ids.existingSecret | default .Values.global.existingSecret }}
                  key: {{ .Values.postgres.ids.existingSecretKeys.password }}
          {{- else }}
              value: {{ .Values.postgres.ids.password | quote }}
          {{- end }}
            - name: POSTGRES_DB
          {{- if or .Values.postgres.ids.existingSecret .Values.global.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.ids.existingSecret | default .Values.global.existingSecret }}
                  key: {{ .Values.postgres.ids.existingSecretKeys.database }}
          {{- else }}
              value: {{ .Values.postgres.ids.database | quote }}
          {{- end }}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
        labels:
          {{- include "postgres.ids.pvc.labels" . | nindent 10 }}
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.global.storageClassName }}
        storageClassName: {{ .Values.global.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgres.data.pvcSize | default "1Gi" }}
{{- end }}
