{{- if .Values.postgres.data.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgres.data.name }}
  labels:
    {{- include "postgres.data.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Values.postgres.data.name }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "postgres.data.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgres.data.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.data.image }}
          ports:
            - containerPort: {{ .Values.postgres.data.port | default "5432" }}
          env:
            - name: POSTGRES_USER
          {{- if or .Values.postgres.data.existingSecret .Values.global.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.data.existingSecret | default .Values.global.existingSecret }}
                  key: {{ .Values.postgres.data.existingSecretKeys.user }}
          {{- else }}
              value: {{ .Values.postgres.data.user | quote }}
          {{- end }}
            - name: POSTGRES_PASSWORD
          {{- if or .Values.postgres.data.existingSecret .Values.global.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.data.existingSecret | default .Values.global.existingSecret }}
                  key: {{ .Values.postgres.data.existingSecretKeys.password }}
          {{- else }}
              value: {{ .Values.postgres.data.password | quote }}
          {{- end }}
            - name: POSTGRES_DB
          {{- if or .Values.postgres.data.existingSecret .Values.global.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.data.existingSecret | default .Values.global.existingSecret }}
                  key: {{ .Values.postgres.data.existingSecretKeys.database }}
          {{- else }}
              value: {{ .Values.postgres.data.database | quote }}
          {{- end }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.postgres.data.port | default "5432" }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - $POSTGRES_USER
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
        labels:
          {{- include "postgres.data.pvc.labels" . | nindent 10 }}
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.global.storageClassName }}
        storageClassName: {{ .Values.global.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgres.data.pvcSize | default "1Gi" }}
{{- end }}
