{{- if .Values.postgres.ids.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-dump-cronjob" .Values.postgres.ids.name }}
spec:
  schedule: {{ .Values.postgres.ids.backup.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: postgres-dump
              image: {{ .Values.postgres.ids.image }}
              env:
                - name: POSTGRES_USER
              {{- if or .Values.postgres.ids.existingSecret .Values.global.existingSecret }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.postgres.ids.existingSecret | default .Values.global.existingSecret }}
                      key: {{ .Values.postgres.ids.existingSecretKeys.user }}
              {{- else }}
                  value: {{ .Values.postgres.ids.user | quote }}
              {{- end }}
                - name: POSTGRES_PASSWORD
              {{- if or .Values.postgres.ids.existingSecret .Values.global.existingSecret }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.postgres.ids.existingSecret | default .Values.global.existingSecret }}
                      key: {{ .Values.postgres.ids.existingSecretKeys.password }}
              {{- else }}
                  value: {{ .Values.postgres.ids.password | quote }}
              {{- end }}
                - name: POSTGRES_HOST
                  value: {{ .Values.postgres.ids.host | quote }}
                - name: POSTGRES_PORT
                  value: {{ .Values.postgres.ids.port | quote }}
              command: ["/bin/sh", "-c"]
              args:
                - |
                  BACKUP_DATE=$(date +%F_%H%M%S)
                  echo "Starting PostgreSQL IDs backup for date: $BACKUP_DATE"
                  
                  echo "*:*:*:${POSTGRES_USER}:${POSTGRES_PASSWORD}" > ~/.pgpass
                  chmod 600 ~/.pgpass
                  pg_dumpall -h ${POSTGRES_HOST} -p ${POSTGRES_PORT} -U ${POSTGRES_USER} \
                    | gzip -4 > /dump/postgres-ids-$BACKUP_DATE.sql.gz
                  
                  echo "PostgreSQL IDs backup completed at $(date)"
                  
                  # Clean up old backups based on limit
                  BACKUP_LIMIT={{ .Values.postgres.ids.backup.limit | default 10 }}
                  echo "Keeping only $BACKUP_LIMIT most recent PostgreSQL IDs backups"
                  
                  # Clean up old backup files
                  cd /dump && ls -t postgres-ids-*.sql.gz 2>/dev/null | tail -n +$((BACKUP_LIMIT + 1)) | xargs -r rm -f
                  
                  echo "PostgreSQL IDs backup cleanup completed. Current backups:"
                  ls -la /dump/postgres-ids-*.sql.gz 2>/dev/null | sort || echo "No backup files found"
              volumeMounts:
                - name: postgres-dump
                  mountPath: /dump
          volumes:
            - name: postgres-dump
              persistentVolumeClaim:
                claimName: {{ printf "%s-dump-pvc" .Values.postgres.ids.name }}
          restartPolicy: OnFailure
{{- end }}