name: CI - Validate Helm Chart

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'obiba-opal/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches:
      - master
      - dev
    paths:
      - 'obiba-opal/**'
      - '.github/workflows/ci.yml'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v4.3.0

    - name: Lint Helm chart
      run: |
        helm lint obiba-opal

    - name: Validate Helm templates
      run: |
        helm template obiba-opal obiba-opal/ --debug

    - name: Test Helm package
      run: |
        mkdir -p test-packages
        helm package obiba-opal --destination test-packages
        echo "Package created successfully:"
        ls -la test-packages/

    - name: Validate Chart.yaml
      run: |
        # Check required fields in Chart.yaml
        if ! grep -q "^apiVersion:" obiba-opal/Chart.yaml; then
          echo "Error: Missing apiVersion in Chart.yaml"
          exit 1
        fi
        if ! grep -q "^name:" obiba-opal/Chart.yaml; then
          echo "Error: Missing name in Chart.yaml"
          exit 1
        fi
        if ! grep -q "^version:" obiba-opal/Chart.yaml; then
          echo "Error: Missing version in Chart.yaml"
          exit 1
        fi
        echo "Chart.yaml validation passed"

    - name: Test with different values
      run: |
        # Test with MongoDB enabled
        helm template obiba-opal obiba-opal/ --set mongo.enabled=true --debug
        
        # Test with PostgreSQL enabled
        helm template obiba-opal obiba-opal/ --set postgres.data.enabled=true --debug
        
        # Test with Ingress enabled
        helm template obiba-opal obiba-opal/ --set ingress.enabled=true --debug
        
        echo "All template tests passed"

    - name: Validate YAML syntax
      run: |
        # Check all YAML files for syntax errors
        find obiba-opal/templates -name "*.yaml" -exec echo "Validating {}" \; -exec helm template obiba-opal obiba-opal/ --show-only {} \;
