name: Release Helm Chart

on:
  push:
    branches:
      - master
    paths:
      - 'opal/**'
      - '.github/workflows/release.yml'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v4.3.0

    - name: Package chart
      run: |
        mkdir -p .cr-release-packages
        helm package opal --destination .cr-release-packages

    - name: Create index.yaml
      run: |
        mkdir -p docs
        helm repo index .cr-release-packages --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
        mv .cr-release-packages/*.tgz docs/
        mv .cr-release-packages/index.yaml docs/

    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
